import type { Control } from "@/lib/rules/types";

/**
 * Controls a team can answer about with "in place", "partial" or "missing". The gap check asks only
 * the controls that evidence an obligation which applies; the action plan turns missing and partial
 * ones into prioritised actions. Every obligation in obligations.ts must be covered by at least one
 * control (checked in pack.test.ts).
 */
export const CONTROLS: Control[] = [
  { id: "C_AI_LITERACY", question: "Do you have an AI literacy programme: a policy plus role-based training for the people who operate or use AI systems?", good: "A written policy, a training plan by role, and completion records.", action: "Create an AI literacy policy and a role-based training plan, and record who completed it.", obligations: ["O_AI_LITERACY"], owner: "HR" },
  { id: "C_PROHIBITED_REMEDIATION", question: "Has the prohibited practice been removed or redesigned out of the system, with legal advice recorded?", good: "A signed-off redesign and a legal opinion on file.", action: "Stop use now, redesign the system so it no longer performs the prohibited practice, and get qualified legal advice.", obligations: ["O_STOP_PROHIBITED", "O_STOP_PROHIBITED_NEW"], owner: "Leadership" },

  { id: "C_AI_DISCLOSURE", question: "Does the system tell users up front, in a clear and accessible way, that they are interacting with an AI?", good: "A visible notice at the first interaction that passes an accessibility check.", action: "Add a clear 'you are talking to an AI' notice at the start of the interaction and check it is accessible.", obligations: ["O_T50_1_DISCLOSE_AI"], owner: "Product" },
  { id: "C_CONTENT_MARKING", question: "Are generated texts, images, audio or video marked as AI-generated in a machine-readable way?", good: "Watermarks or metadata that survive normal use, with test results.", action: "Implement machine-readable marking (metadata, watermarking or provenance) for generated outputs and test it.", obligations: ["O_T50_2_MARK_CONTENT"], owner: "Engineering" },
  { id: "C_EXPOSED_PERSONS_NOTICE", question: "Are people exposed to emotion recognition or biometric categorisation told how the system operates?", good: "A notice shown before exposure, reviewed against data protection law.", action: "Add a notice for exposed people and review the processing with your data protection team.", obligations: ["O_T50_3_INFORM_EXPOSED"], owner: "Product" },
  { id: "C_DEEPFAKE_LABEL", question: "Is AI-generated or manipulated image, audio or video clearly disclosed as such?", good: "A visible label, with an appropriate lighter form for clearly artistic or satirical work.", action: "Label deep-fake content as artificially generated or manipulated.", obligations: ["O_T50_4A_DISCLOSE_DEEPFAKE"], owner: "Product" },
  { id: "C_TEXT_DISCLOSURE", question: "Is AI-generated text published to inform the public disclosed, or covered by human editorial responsibility?", good: "A disclosure label or a documented editorial-responsibility process.", action: "Disclose AI-generated public-interest text, or put human editorial review and responsibility in place.", obligations: ["O_T50_4B_DISCLOSE_TEXT"], owner: "Product" },

  { id: "C_RISK_MANAGEMENT", question: "Is there a documented risk management process that runs across the system's lifecycle, with testing against defined metrics?", good: "A living risk file reviewed regularly, with test reports.", action: "Set up a lifecycle risk management process: identify risks to health, safety and fundamental rights, mitigate them and test before launch.", obligations: ["O_HR_RISK_MANAGEMENT"], owner: "Legal / Compliance" },
  { id: "C_DATA_GOVERNANCE", question: "Are training, validation and testing data governed and checked for bias, quality and representativeness?", good: "Data sheets, a bias assessment and a data quality report.", action: "Document data origin and preparation, run a bias assessment and fix data gaps.", obligations: ["O_HR_DATA_GOVERNANCE", "O_DEP_INPUT_DATA"], owner: "Data" },
  { id: "C_TECHNICAL_DOCUMENTATION", question: "Does complete technical documentation exist (Annex IV) and is it kept up to date?", good: "An Annex IV file, or the simplified SME/small mid-cap form.", action: "Draw up the Annex IV technical documentation and keep it current.", obligations: ["O_HR_TECHNICAL_DOCUMENTATION"], owner: "Engineering" },
  { id: "C_LOGGING", question: "Does the system automatically log events, and are logs kept for at least six months?", good: "Automatic event logging with a retention setting of six months or more.", action: "Enable automatic event logging and set retention to at least six months.", obligations: ["O_HR_LOGGING", "O_HR_RECORDS_LOGS", "O_DEP_LOGS"], owner: "Engineering" },
  { id: "C_INSTRUCTIONS_FOR_USE", question: "Do deployers receive instructions for use covering purpose, accuracy, risks, oversight measures and how to read the logs?", good: "A complete instructions-for-use document.", action: "Write instructions for use that cover the Article 13 content.", obligations: ["O_HR_INSTRUCTIONS", "O_DEP_USE_ACCORDING_TO_INSTRUCTIONS"], owner: "Product" },
  { id: "C_HUMAN_OVERSIGHT", question: "Is human oversight designed in (understand, override, stop) and assigned to competent, authorised people?", good: "Oversight design, named roles and training records.", action: "Design oversight into the interface (override and stop) and assign trained, authorised people.", obligations: ["O_HR_HUMAN_OVERSIGHT", "O_DEP_HUMAN_OVERSIGHT"], owner: "Product" },
  { id: "C_ACCURACY_SECURITY", question: "Have accuracy, robustness and cybersecurity (including AI-specific attacks) been tested and declared?", good: "Test results, declared accuracy metrics and a security assessment.", action: "Test accuracy and robustness, run an AI-specific security assessment and declare the accuracy metrics.", obligations: ["O_HR_ACCURACY_ROBUSTNESS_SECURITY"], owner: "Security" },
  { id: "C_QMS", question: "Is there a documented quality management system covering compliance strategy, testing, data, monitoring and incidents?", good: "QMS documentation proportionate to your size.", action: "Establish a documented quality management system.", obligations: ["O_HR_QMS"], owner: "Legal / Compliance" },
  { id: "C_CONFORMITY_ASSESSMENT", question: "Has the conformity assessment been completed, with an EU declaration of conformity and CE marking?", good: "A conformity assessment record, a signed declaration and CE marking.", action: "Complete the conformity assessment, sign the EU declaration of conformity and affix the CE marking.", obligations: ["O_HR_CONFORMITY_ASSESSMENT", "O_HR_DECLARATION_CE"], owner: "Legal / Compliance" },
  { id: "C_REGISTRATION", question: "Is the system (or your use of it) registered in the EU database where required?", good: "An EU database entry.", action: "Register the system, or your use of it, in the EU database.", obligations: ["O_HR_REGISTRATION", "O_EXC_REGISTER", "O_DEP_PUBLIC_REGISTRATION"], owner: "Legal / Compliance" },
  { id: "C_PROVIDER_LABELLING", question: "Do the system or its documentation show your name and contact address, and does it meet accessibility requirements?", good: "Labelling and an accessibility statement.", action: "Add your name and contact address and confirm accessibility compliance.", obligations: ["O_HR_PROVIDER_IDENTIFICATION"], owner: "Product" },
  { id: "C_POST_MARKET", question: "Is there a post-market monitoring plan that actively collects performance data after launch?", good: "A monitoring plan within the technical documentation, with periodic reports.", action: "Write a post-market monitoring plan and start collecting performance data.", obligations: ["O_HR_POST_MARKET_MONITORING"], owner: "Engineering" },
  { id: "C_INCIDENT_RESPONSE", question: "Is there an incident process that can report serious incidents to authorities within 15, 10 or 2 days, and monitor operation?", good: "A runbook with deadlines, owners and a monitoring procedure.", action: "Create a serious-incident response runbook with the 15-, 10- and 2-day deadlines and a monitoring procedure.", obligations: ["O_HR_INCIDENT_REPORTING", "O_DEP_MONITOR_REPORT"], owner: "Legal / Compliance" },
  { id: "C_CORRECTIVE_ACTIONS", question: "Can you bring a non-conforming system into conformity, withdraw or recall it, and answer authorities' requests?", good: "A documented corrective action and authority-request procedure.", action: "Document how you would correct, withdraw or recall the system and respond to authorities.", obligations: ["O_HR_CORRECTIVE_ACTIONS"], owner: "Legal / Compliance" },
  { id: "C_AUTHORISED_REPRESENTATIVE", question: "Have you appointed an EU authorised representative by written mandate?", good: "A signed mandate.", action: "Appoint an authorised representative established in the EU.", obligations: ["O_HR_AUTHORISED_REPRESENTATIVE", "O_GPAI_AUTHORISED_REPRESENTATIVE"], owner: "Legal / Compliance" },
  { id: "C_EXCEPTION_ASSESSMENT", question: "Is the Article 6(3) 'not high-risk' conclusion documented in writing?", good: "A written assessment ready to hand to authorities.", action: "Write down the Article 6(3) assessment before launch.", obligations: ["O_EXC_DOCUMENT"], owner: "Legal / Compliance" },
  { id: "C_WORKER_INFORMATION", question: "Have workers and their representatives been informed before the system is used at work?", good: "A notification and consultation record.", action: "Inform workers' representatives and affected workers before use.", obligations: ["O_DEP_INFORM_WORKERS"], owner: "HR" },
  { id: "C_DPIA", question: "Is a data protection impact assessment done, using the provider's information?", good: "A completed data protection impact assessment.", action: "Carry out the GDPR data protection impact assessment using the provider's instructions for use.", obligations: ["O_DEP_DPIA"], owner: "Legal / Compliance" },
  { id: "C_FRIA", question: "Has a fundamental rights impact assessment been done before first use?", good: "A completed assessment notified to the market surveillance authority.", action: "Carry out and notify the fundamental rights impact assessment before first use.", obligations: ["O_DEP_FRIA"], owner: "Legal / Compliance" },
  { id: "C_AFFECTED_PERSONS", question: "Are affected people told they are subject to the system, and can you give them an explanation of decisions?", good: "A notice and an explanation procedure.", action: "Add a notice for affected people and an explanation procedure for decisions.", obligations: ["O_DEP_INFORM_AFFECTED_PERSONS", "O_DEP_EXPLANATION"], owner: "Product" },
  { id: "C_SUPPLIER_AGREEMENTS", question: "Do you have written agreements with suppliers of AI models, tools or components you integrate?", good: "Supplier contracts with compliance information and access clauses.", action: "Put written agreements in place with each supplier of integrated AI components.", obligations: ["O_ART25_SUPPLIER_AGREEMENTS"], owner: "Legal / Compliance" },
  { id: "C_ROLE_CHANGE", question: "Have you taken on provider responsibilities after rebranding, modifying or repurposing the system?", good: "Allocated responsibilities and handover documentation from the original provider.", action: "Assume the provider obligations and obtain the original provider's documentation and technical access.", obligations: ["O_ART25_PROVIDER_DUTIES"], owner: "Leadership" },
  { id: "C_IMPORTER_CHECKS", question: "Do you verify conformity, CE marking, documents and the authorised representative before placing a system on the market?", good: "An importer verification checklist.", action: "Introduce an importer verification checklist.", obligations: ["O_IMP_VERIFY"], owner: "Legal / Compliance" },
  { id: "C_DISTRIBUTOR_CHECKS", question: "Do you verify CE marking and documentation before making a system available?", good: "A distributor verification checklist.", action: "Introduce a distributor verification checklist.", obligations: ["O_DIST_VERIFY"], owner: "Legal / Compliance" },
  { id: "C_GPAI_DOCUMENTATION", question: "Do you have model documentation, downstream information, a copyright policy and a published training-content summary?", good: "Annex XI and XII documentation, a copyright policy and a public summary.", action: "Prepare the model documentation, downstream information, copyright policy and public training-content summary.", obligations: ["O_GPAI_TECH_DOC", "O_GPAI_DOWNSTREAM_INFO", "O_GPAI_COPYRIGHT_POLICY", "O_GPAI_TRAINING_SUMMARY"], owner: "Engineering" },
  { id: "C_GPAI_SYSTEMIC_RISK", question: "For a systemic-risk model: have you notified the Commission, run adversarial testing, assessed systemic risks and set up incident reporting and cybersecurity?", good: "Notification, evaluation reports, a systemic risk assessment, an incident log and a security assessment.", action: "Notify the Commission, run adversarial evaluations, assess and mitigate systemic risks, and set up incident reporting and cybersecurity.", obligations: ["O_GPAI_SYSTEMIC_NOTIFY", "O_GPAI_SYSTEMIC_EVALUATE", "O_GPAI_SYSTEMIC_INCIDENTS_SECURITY"], owner: "Security" },
];
