import type { UIMessage } from "ai";
import { rewriteCitationsInParts } from "@/lib/citations";
import { blocksToMarkdown } from "@/lib/aegis-blocks";
import type { UISource } from "@/types/data";

export type ExportOptions = {
  aiName: string;
  /** Date the built-in legal reference was last reviewed (REFERENCE_REVIEWED_ON). */
  referenceReviewedOn: string;
  /** Label each turn "You" / the assistant name. Off for a single-answer export. */
  roleLabels?: boolean;
  date?: Date;
};

const WELCOME_PREFIX = "welcome-";

function textParts(message: UIMessage): string[] {
  return message.parts
    .filter((p) => p.type === "text")
    .map((p) => (p as { text?: string }).text ?? "");
}

function sourcesOf(message: UIMessage): UISource[] {
  const part = message.parts.find((p) => p.type === "data-sources") as
    | { data?: UISource[] }
    | undefined;
  return Array.isArray(part?.data) ? part.data : [];
}

function sourceLine(s: UISource, index: number): string {
  const n = s.number ?? index + 1;
  // Brackets in a title would break the markdown link.
  const title = s.title.replace(/[[\]]/g, "");
  const label = /^https?:\/\//i.test(s.url) ? `[${title}](${s.url})` : title;
  const meta = [s.site, s.publishedDate].filter(Boolean).join(" · ");
  return `${n}. ${label}${meta ? ` — ${meta}` : ""}`;
}

/**
 * One turn as markdown, or null when it has nothing worth exporting (the
 * welcome message, or an assistant turn that only ran tools).
 *
 * Assistant text gets the same citation canonicalization the chat UI applies,
 * so the numbers in the file match what was on screen, and the answer's
 * Sources box is appended as a numbered list.
 */
function turnToMarkdown(message: UIMessage, opts: ExportOptions): string | null {
  if (message.id.startsWith(WELCOME_PREFIX)) return null;
  if (message.role !== "user" && message.role !== "assistant") return null;

  // The summary card / next-step buttons are UI blocks: flatten them to plain Markdown first.
  const texts =
    message.role === "assistant"
      ? rewriteCitationsInParts(textParts(message).map(blocksToMarkdown))
      : textParts(message);
  const body = texts.map((t) => t.trim()).filter(Boolean).join("\n\n");
  if (!body) return null;

  const sources = message.role === "assistant" ? sourcesOf(message) : [];
  const sourceBlock =
    sources.length > 0
      ? `\n\n**Sources**\n\n${sources.map(sourceLine).join("\n")}`
      : "";
  const label = opts.roleLabels
    ? `**${message.role === "user" ? "You" : opts.aiName}**\n\n`
    : "";
  return `${label}${body}${sourceBlock}`;
}

/** Returns the markdown document, or null when there is nothing to export. */
export function buildExportMarkdown(
  messages: UIMessage[],
  opts: ExportOptions
): string | null {
  const turns = messages
    .map((m) => turnToMarkdown(m, opts))
    .filter((t): t is string => t !== null);
  if (turns.length === 0) return null;

  const date = (opts.date ?? new Date()).toISOString().slice(0, 10);
  const header = [
    `# ${opts.aiName}: EU AI Act assessment`,
    `*Exported ${date}. Generated by an AI system (${opts.aiName}) as a first-line assessment, not legal advice. Review by a responsible person and confirm with qualified counsel before relying on it or sharing it as final. The built-in legal reference was last reviewed on ${opts.referenceReviewedOn}; later changes to the law may not be reflected.*`,
  ].join("\n\n");

  return `${header}\n\n---\n\n${turns.join("\n\n---\n\n")}\n`;
}

/** Browser-only: saves text as a .md file. */
export function downloadMarkdown(filename: string, markdown: string): void {
  const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  // Revoke after the download has started (immediate revoke fails in some browsers).
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
